### ISSUE TITLE
errors installing SDK in windows 10

### ISSUE THREAD

**Issue by keven-correa** [fonoster/fonoster#102]
**Describe the bug**

**To Reproduce**
1. Go to 'npm install @fonos/sdk '
2. Type '....'
3. Then, '....'
![image](https://user-images.githubusercontent.com/64440171/122990933-79e95780-d372-11eb-97e1-1374d7e60b79.png)

![image](https://user-images.githubusercontent.com/64440171/122990982-8372bf80-d372-11eb-9beb-81eb1e1d973f.png)

**Expected behavior**

**Screenshots**

**System information (please complete the following):**
 - OS: Windows 10
 - NodeJS 14.16.0, NPM 6.14.11
 - CTL version 0.1.1-alpha.0

**Additional context**

**Comment by psanders** [comment]
Thanks for reporting the issue. We will try to reproduce the issue and get back to you.

**Comment by psanders** [comment]
@Wardner can you take a look at this and try to reproduce it?

**Comment by wardner** [comment]
Hi, @K-Correa.
I could'nt reproduce it, but here are some ways that may possibly solve it.

1. Disable your anti-virus. Then install the dependency again.

2. Close all VS code tabs open. Open the bash in administrator mode, and then install the dependency.
