### ISSUE TITLE
Error Typing "fonos" in Windows, First Time 

### ISSUE THREAD

**Issue by BrayanMnz** [fonoster/fonoster#168]
**Describe the bug**

The problem here is after install Fonos and try to run it at first time. 

When typing fonos on any command line. i.e cmd, bash, PowerShell
It throws a ".Fonos" directory missing. 

To immediately fix it, just need to create a directory called .fonos at the route specified.

**To Reproduce**
At first time running fonos on Windows: 

  1. Go to 'cmd, git bash or PowerShell'
  2. Type ' fonos '
  3. Then, 'It throws a ".Fonos" directory missing error'

**Expected behavior**
The Fonos command to run properly, you may need to add the directory creation "automatically" in the case of using Windows.

**Screenshots**

**System information (please complete the following):**
 - OS: Windows 10
 - NodeJS, NPM versions [e.g. v14.17.4, 6.14.14]
 - CTL version [e.g. 0.1 ]

**Additional context**

**Comment by psanders** [comment]
Thanks for reporting the issue. I will push a fix and let you know.

**Comment by psanders** [comment]
I push a patch to solve this. Can you confirm it works properly with`0.1.27`?

**Comment by BrayanMnz** [comment]
In version `0.1.27` the error is not thrown. 
Bug can be closed.

**Comment by psanders** [comment]
Thanks.
