### ISSUE TITLE
Community Dashboard

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#173]
**Is your feature request related to a problem? Please describe.**
The ctl tool is cool but for some, a Web UI is more user-friendly...

**Describe the solution you'd like**
We create basic Web UI covering the same functionalities we have in the ctl

**Describe alternatives you've considered**
None

**Additional context**
A good starting point for this is the [OpenAPI spec](https://api.fonoster.io/api/api-docs/#/).

**Comment by efraa** [comment]
@psanders  This issue is a duplicate of https://github.com/fonoster/roadmap/issues/15
