### ISSUE TITLE
Implement a docker-in-docker installer

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#200]
Please help test this.

I like to know if it works properly especially on Windows, OSX. If you found an error please consider submiting a PR

**Comment by xpostudio4** [comment]
Installed it successfully with:

- MacOS BigSur Version. 11.6 (20G165)
- Docker Desktop 3.2.2 (61853)
- Engine 20.10.5
- Compose 1.28.5
- Snyk v1.432.0

**Comment by psanders** [comment]
@xpostudio4 

Thanks for your collaboration!
