### ISSUE TITLE
Basic Network Script Error

### ISSUE THREAD

**Issue by harish-chander** [fonoster/fonoster#201]
**Getting Docker compose error on ./basic-network.sh stop|start Script**

When i run ./basic-network.sh stop or start i am getting the following error
```
ERROR: The Compose file './01_api.yml' is invalid because:
Unsupported config option for services.agents: 'extends'
Unsupported config option for services.auth: 'extends'
Unsupported config option for services.callmanager: 'extends'
Unsupported config option for services.domains: 'extends'
Unsupported config option for services.numbers: 'extends'
Unsupported config option for services.projects: 'extends'
Unsupported config option for services.providers: 'extends'
Unsupported config option for services.storage: 'extends'
Unsupported config option for services.users: 'extends'
```
Using Docker
```
Client:
 Version:           20.10.5+dfsg1
 API version:       1.41
 Go version:        go1.15.9
 Git commit:        55c4c88
 Built:             Wed Aug  4 19:55:57 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.5+dfsg1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.9
  Git commit:       363e9a8
  Built:            Wed Aug  4 19:55:57 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.5~ds1
  GitCommit:        1.4.5~ds1-2
 runc:
  Version:          1.0.0~rc93+ds1
  GitCommit:        1.0.0~rc93+ds1-5+b2
 docker-init:
  Version:          0.19.0
  GitCommit:

```
**To Reproduce**
1. Go to '/opt/fonos' or '/root/fonoster/operator'
2. Type './basic-network.sh stop'
3. See error

**Expected behavior**
Normal behavior should be the docker containers will stop on stop command and start on start command and apply the new .env params

**System information (please complete the following):**
 - OS: Debian 11
 -  Docker 20.10.05

**Comment by psanders** [comment]
I'm unable to reproduce this problem, but I suspect it has to do with the docker-compose version. You try two things:

1. Update your docker-compose
2. Try to manually lower the version on the compose files to maybe `3.3`

Let me know if any of this works.

> We recently updated the API version from 3.3 to 3.7

**Comment by harish-chander** [comment]
Thanks . Updating the docker-compose worked . working with 3.7 template as well
