### ISSUE TITLE
Multiple Features

### ISSUE THREAD

**Issue by 9mido** [fonoster/fonoster#205]
Holding:
Put the user on hold with waiting music/recording before a call starts and during the call 
When on hold, be able to make another call with someone else but still be able to return back to the on hold caller or put them in a queue for someone else (parking). 

Transfers:
Warm/cold transfers to another phone number
There should be a fallback in case of getting stuck where the number we are transferring to does not answer.

Conference:
Adding multiple people to a single call
Password for entering into the conference

Extensions:
Dial an phone number extension

Call statuses:
There should be a way for a user to see who is calling them, if the call is disconnected, busy, on hold, mute, etc.

**Comment by psanders** [comment]
Hi @9mido 

Thanks for submitting the issue. The template is only for reference to make requests easy for you. Do you care to review and complete the feature request?

**Comment by 9mido** [comment]
@psanders You're welcome. I am a user of Twilio and would much rather use your project instead. These are just some ideas for some common use cases I have with Twilio that I would like to see implemented here. I am unable make any coding changes as I do not have the knowledge of your tech stack. I might be able to review things if someone else codes the features in the future but it is unlikely as I might be busy with something else at that time.

**Comment by psanders** [comment]
Perhaps I could be more clear. We have a specific [format](https://github.com/fonoster/fonoster/issues/new?assignees=&labels=&template=feature_request.md&title=) for issue requests, so we can do proper tracking and follow-up. This feels more appropriate for [Discussions](https://github.com/fonoster/fonoster/discussions/new)
