### ISSUE TITLE
Please add sms 

### ISSUE THREAD

**Issue by Windowsground** [fonoster/fonoster#208]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by psanders** [comment]
Hi @Windowsground 

Thanks for submitting the issue. The template is only for reference to make requests easy for you. Do you care to review your feature request?

Otherwise, you could try posting on [discussions](https://github.com/fonoster/fonoster/discussions)

**Comment by BrayanMnz** [comment]
This is not a issue, maybe we should also close this one. FYI @psanders

**Comment by psanders** [comment]
Closing this for now, but feel free to reopen.

> We are ok with having here feature requests as long as they are articulated.
