### ISSUE TITLE
please change the name

### ISSUE THREAD

**Issue by omiinaya** [fonoster/fonoster#213]
i want to try this but i dont want the word fonoster anywhere near my package.json

**Comment by s0urfruit** [comment]
I'm sorry but what the fuck is this issue

**Comment by psanders** [comment]
@omiinaya 

We like to keep Github Issues only for bugs or feature requests. Changing the name of the project doesn't fit in either category. 

If for some odd reason the name of the project is offensive (like it means something bad in some language) please use Github Discussions so at least we are aware. 

Closing this...
