### ISSUE TITLE
traefik letencrypt not setting correctly

### ISSUE THREAD

**Issue by harish-chander** [fonoster/fonoster#214]
**Describe the bug**
I have enabled letsencrypt  and the certificate is getting generated correctly and mapping to the container however the traefik is still using self signed certificate instead of generated Certificate

**To Reproduce**
1. Go to '.env' and do the letencrypt required config
2. Type './basic-network stop | start'
3. Then, 'curl to localhost or the public IP or through fonos:auth'

**Expected behavior**
Normal scenario should be that letencrypt will be used for ssl on traefik and fonos cli will connect to it for the call flow

**Screenshots**
[ssl cert details](https://pasteboard.co/pmDYycDaeflW.png)
[curl screenshot](https://pasteboard.co/A0fDZbl3HpIH.png)

**System information (please complete the following):**
 - OS: Debian 10
 - version : Fonoster 0.2.14

**Comment by psanders** [comment]
Thanks for the detailed report.

I wonder if somehow the `basic-network.sh` script is picking up the `noencrypt.yml` instead of `letscrypt.yml`

**Comment by harish-chander** [comment]
I thought the same let me check the script and get back to you

**Comment by harish-chander** [comment]
I checked it is using the secure option and invoking the letsencrypt.yml , Also the acme.json is mounted on the container .
Which is the path for the traefik conf in the folder . so i can troubleshoot it more .

**Comment by harish-chander** [comment]
Sorted traefik was not able to find the acme.json 'le' resolver so from reason , Added 777 permission for the config folder and it is fixed . Used docker logs and enable logs on the letsencrypt.yml and added dev.yml to basic-networking script to find the error

**Comment by psanders** [comment]
@harish-chander 

Did use the Docker-in-Docker installer? I'm curious about why it didn't have the correct permission.

**Comment by harish-chander** [comment]
@psanders 
   No it was normal DO instance . It was a issue from my side . i was playing with some users and screwed up the permission .Nothing from the fonoster project side

**Comment by psanders** [comment]
Makes sense . Thank you.
