### ISSUE TITLE
cannot create new account

### ISSUE THREAD

**Issue by jonathan-chin** [fonoster/fonoster#220]
I visited `https://console.fonoster.io/` and clicked on `Sign in with Github`.

I got put through the usual auth workflow and authorized the app. but then ... nothing happens. I'm still on the same screen with `Sign in with Github`. Subsequent presses of the button does nothing.

Looking at the console log, I see this error: `Manifest: Line: 5, column: 11, Syntax error.`

Investigating further, the manifest.json file has this: `"src": /favicon/android-icon-36x36.png",` which is missing a " at the start of the value definition. but is a broken manifest file enough to halt the whole process?

**Comment by psanders** [comment]
We are investigating this issue. 

It seems to be related to email privacy (we need the email to create the account). It's not clear what's causing this issue, but I am actively searching for a solution.

**Comment by psanders** [comment]
@jonathan-chin
@lilcode-dev

I pushed a change that should fix this issue. Can you verify?

**Comment by lilcode-dev** [comment]
> @jonathan-chin @lilcode-dev
> 
> I pushed a change that should fix this issue. Can you verify?

All correct, it already shows me the access key id and acces key secret

**Comment by psanders** [comment]
Sounds good. I will keep this open for a few days, and will continue to monitor to make sure it doesn't happens again.

**Comment by jonathan-chin** [comment]
ok, can confirm that this works now. However, when I log in, I see this at the top of the screen:

`Jon Chin - null`

What is null supposed to house/represent?

**Comment by psanders** [comment]
It's supposed to have your email, but I can see it failing if your email is private. I will push a quick fix. Thanks!

**Comment by psanders** [comment]
I had no additional reports of this issue. I will close this but feel free to re-open if it happens again.
