### ISSUE TITLE
I can't sign up with github

### ISSUE THREAD

**Issue by lilcode-dev** [fonoster/fonoster#221]
After installing the Fonoster CTL, I went to ` https://console.fonoster.io/`, I tried to register with `sign in with Github` dog after giving it permission from github it does not go to the next step.

**System information:**
 - OS: Windows 10
 - NodeJS, NPM versions: v16.13.0, v8.1.0
 - Fonoster CTL version : 0.2.18

**Comment by psanders** [comment]
@lilcode-dev 

Thanks for reporting the issue. This was reported before on this [thread](https://github.com/fonoster/fonoster/issues/220). I'm closing this one so we don't have a duplicate.
