### ISSUE TITLE
Abdousry602@gmail.com 

### ISSUE THREAD

**Issue by AbdoAyad2** [fonoster/fonoster#223]
**Describe the bug**

**To Reproduce**
2. Type '....'
3. Then, '....'

**Expected behavior**

**Screenshots**

**System information (please complete the following):**
 - OS: [e.g. Linux]
 - NodeJS, NPM versions [e.g. v14.16.0, 7.10.0]
 - CTL version [e.g. 0.1 ]

**Additional context**

**Comment by psanders** [comment]
Nonsense.
