### ISSUE TITLE
Prefix accessKeyId on Users and Projects

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#230]
**Is your feature request related to a problem? Please describe.**
The pattern on the `accessKeyId` for Users and Projects looks exactly the same which sometimes causes confusion.

**Describe the solution you'd like**
Add a prefix so it is easy to identify the type of account. This enhancement will bring the following changes:

1. User's `accessKeyId` will now have the `US` prefix (i.e `US618572e3ec11d10600000001`)
2. Project's `accessKeyId` will now have `PJ` prefix (i.e `PJ618688e35315720700000001`)

**Describe alternatives you've considered**
None

**Additional context**
NA

**Comment by BrayanMnz** [comment]
This one has already been fixed with commit [eb9a83](https://github.com/fonoster/fonoster/commit/eb9a83446cd43dca30e70dd17df7d9a27209eb7b), maybe should also be closed. 

For your approbal @psanders
