### ISSUE TITLE
It would be nice to know which project is the default project (on the CLI)

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#233]
**Is your feature request related to a problem? Please describe.**
At the moment there is no way to tell which project is set to be the default on the CLI.

**Describe the solution you'd like**
It would be nice to have an indicator so we know which one is the "default". For example, we could mark the default project with an `*`.

```bash
$ fonoster projects:ls
Ref / Access Key Id           Name        
PJ619154d081467a0700000001    Acme Corps *
PJ879134d081567g0h00000001   Walmart North
```

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by BrayanMnz** [comment]
With default project it means "current" project ?

**Comment by psanders** [comment]
Yup. Current.

**Comment by abheekda1** [comment]
If anyone has any pointers I'd love to give this a shot.

**Comment by BrayanMnz** [comment]
I think that this is currently working on recently version of Fonoster, on the User Interface _**Just for Beta Tester at this moment**_
we can easily select the project from a dropdown and the selected one keeps at the top of the dropdown saying that its the current project. 

Is this as I explained? @psanders

If yes, we can close this issue.

**Comment by psanders** [comment]
@BrayanMnz 

This is an issue with the Command-Line Tool only.

**Comment by psanders** [comment]
This was [solved here.](https://github.com/fonoster/fonoster/issues/445)
