### ISSUE TITLE
Feedback on Getting Started Documentation

### ISSUE THREAD

**Issue by jonathan-chin** [fonoster/fonoster#235]
I have followed the guide available at: https://learn.fonoster.com/docs/getting_started/overview and here is my feedback so far:

`Create a User Account` -> no problem

`Install and setup the CLI` -> no problem

`Create a Project` -> no problems but two things:
- the CLI prompts me to allow 'experiments', but the guide doesn't explain what that is (at least, not at this point). I was hesitant to allow it but I did anyway.
- a quality of life suggestion. when running `fonoster projects:use [ref]`, would it be possible to use the friendly name instead of the id? I come from a Firebase background and their CLI let's me write something like `firebase projects:use share-meals-dev`, where "share-meals-dev" is the project name. it's not a huge issue.

`Configure a Number` -> no problems but the CLI asks me for an "expire" value. from the guide, it's not clear what this is. the only thing I can relate it to is the TTL for a DNS record. the questions in my head are "what unit of measurement is expire using?" and "what happens after a number expires"?

`Create a Voice Application` -> I followed the guide and everything was smooth. however, the last instruction is to use ngrok to expose my server. what do I do with this URL now? my instinct is to log into voip.ms and configure something there. I think that's what I would have to do with Twilio, ie point the number to an endpoint on my server. I held off on that for now and moved onto the next step in the guide.

`Receive and respond to a call` -> it's unclear what command I should run. the documentation says `fonoster numbers:update [ID]` but what does ID represent? the only thing I can think of is to put the url from ngrok from before, so I ran: `fonoster numbers:update https://xxxx-xx-xx-xx-xxx.ngrok.io`. I'm then prompted for an "aor link". I don't even know what AOR stands for.

at this point, I stopped following the guide.

**Comment by psanders** [comment]
This is super useful. Do you care to re-post this at [GH Discussions](https://github.com/fonoster/fonoster/discussions/209) . I will close it as we want to keep issues only for feature requests and bugs 🙂
