### ISSUE TITLE
Outbound calls fail for numbers starting with "+" symbol.

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#252]
**Describe the bug**
Outbound calls fail for numbers starting with "+" symbol

**To Reproduce**
1. Create a new call script using the CallManager
2. Start a call with a Provider that requires E164 Numbers (like Twilio)
3. See error `400 Invalid phone number` or equivalent

**Expected behavior**
The API should send the numbers as input by the users

**Screenshots**

<img width="1133" alt="400 Invalid phone number " src="https://user-images.githubusercontent.com/539774/145084764-d6b1b8a9-17a5-415f-b69f-5a7c520c661f.png">

**System information (please complete the following):**
 - API version [0.2.21 ]

**Additional context**
The root of the issue seems to be at: [call.ts](https://github.com/fonoster/fonoster/blob/5a31e510c928aef7ec60cd1e2e44ed44886d2677/mods/callmanager/src/service/call.ts#L42)

**Comment by nisancigokmen** [comment]
wow. okey dude,
dear,gökmen


Pedro Sanders ***@***.***>, 7 Ara 2021 Sal, 21:23 tarihinde
şunu yazdı:
