### ISSUE TITLE
The TTSPlugin interface has a typo

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#259]
**Describe the bug**

There is a typo in the TTSPlugin interface in the package`@fonoster/tts`. The name of the function `synthetize` is a typo and should be renamed as `synthesize.`

**To Reproduce**
NA

**Expected behavior**
NA

**Screenshots**
NA

**System information (please complete the following):**
NA

**Additional context**

**Comment by gad2103** [comment]
i'm happy to take this on. however, it has downstream effects on at least Rox and anywhere else the lib is imported. how do you recommend fixing across all usage sites where the interface is being implemented?

**Comment by psanders** [comment]
I recommend adding the correct method and keeping the old one (with a deprecation notice). Then, all implementations will need to implement the new method name and maintain the old one as an "alias" until the deprecation is complete.

Leaving all known implementations here, for reference:

https://github.com/fonoster/fonoster/tree/main/mods/googletts
https://github.com/fonoster/pollytts
https://github.com/fonoster/fonoster/tree/main/mods/marytts

**Comment by BrayanMnz** [comment]
Issue still open but has been already merged in [pull/264/commits](https://github.com/fonoster/fonoster/pull/264/commits)

Should this issue be closed or something is missing ?

**Comment by psanders** [comment]
> Issue still open but has been already merged in [pull/264/commits](https://github.com/fonoster/fonoster/pull/264/commits)
> 
> Should this issue be closed or something is missing ?

Good catch. There is no reason to keep this open. Thanks
