### ISSUE TITLE
File retention policy on Rox

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#260]
**Is your feature request related to a problem? Please describe.**

The docker container for [Rox](https://github.com/fonoster/rox) is currently keeping all of the generated media files (e.g. from the TTS engine), which causes an increase in disk utilization.

**Describe the solution you'd like**

We should have a cleanup mechanism to remove unused files. For example,  a cron job that runs every `n` hours and removes files that haven't been accessed for `x` hours.

**Describe alternatives you've considered**

We could add a flag on Rox to avoid storing files.

**Additional context**
None

**Comment by efraa** [comment]
@psanders  https://github.com/fonoster/rox/pull/9
