### ISSUE TITLE
Install script hangs with "Fluentd error" for >= 0.3.0

### ISSUE THREAD

**Issue by baflo** [fonoster/fonoster#292]
**Describe the bug**
I have issues running the install [script on Linux for Docker](https://github.com/fonoster/fonoster/blob/main/docs/operator/deploy-with-docker.md) on version `>= 0.3.0`. (btw, the `jwthelper` image missing for `0.3.3`.)

When running it as given in the docs, I constantly get an error "Fluentd error Error: connect ECONNREFUSED" and the the process hangs.

I tracked it down to the `jwthelper` image, which is called by the `service_creds` and `user_creds` services in the `init.yml` docker-compose file (which can be reproduced with the command I noted in "To Reproduce" below).

The issue occurs because there seems to be a mismatch between where `trust_util.ts` expects the default config file (`/home/fonoster/.fonoster/config`) and where it bound in the `init.yaml` (`/home/fonoster/config`).

Due to this mismatch a log message is sent to Fluentd which causes the process to hang due to unfulfilled tasks?

**To Reproduce**
1. Run `docker run --rm -ti -v $(pwd)/fonoster/config/private_key:/home/fonoster/private_key -v $(pwd)/fonoster/config:/opt/fonoster/config' fonoster/jwthelper:0.3.2`

**Expected behavior**
I expect the script to run through if no default config is given.

**Screenshots**
![image](https://user-images.githubusercontent.com/834350/154632244-1d017103-f05b-4629-9a10-3251b409146a.png)

**System information (please complete the following):**
 - OS:  Linux
 - fonoster image versions: 0.3.0 - 0.3.2

**Additional context**

**Comment by psanders** [comment]
@baflo 

Thanks for the detailed report. 

Can you post the exact installation script you use? Also, is `0.3.3` any better?

(we fixed our ci to include the jwthelper image)

**Comment by baflo** [comment]
@psanders Yes, jwthelpers:v0.3.3 now exists and works :D

**Comment by psanders** [comment]
Very well. Sound like it fixed the issue. Closing here, but feel free to re-open if it happens again.
