### ISSUE TITLE
Volume declaration missing in v0.3.3 install routine

### ISSUE THREAD

**Issue by baflo** [fonoster/fonoster#302]
**Describe the bug**
While running the v0.3.3 install procedure, an error occurs, that a docker compose volume declaration is missing.

**To Reproduce**
See screenshots

**Expected behavior**
The install procedure should run through successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/834350/155940709-5c9c0950-006b-4dda-be86-88b4be21806a.png)

**System information (please complete the following):**
 - OS: Linux
 - Install script using image version v0.3.3

**Additional context**
As discussed in Slack: https://fonoster.slack.com/archives/C01C7NHQJVD/p1645686814273269

**Comment by psanders** [comment]
@baflo 

Thanks for reporting the issue. We finished triaging this and confirm it as a bug. We are currently testing a fix, and hope to have a patch by the end of the week.

**Comment by psanders** [comment]
@baflo 

I merged a fix that solves this issue. Find [here](https://github.com/fonoster/fonoster/blob/0.3/docker/README.md) examples of use. I'm closing this as solved, but feel free to reopen if needed.
