### ISSUE TITLE
Auto generate certificates for the sipproxy

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#308]
**Is your feature request related to a problem? Please describe.**

We must automate the process of creating certificates to secure the path of the sip signaling. This is particularly important to allow connecting to Fonoster's sip proxy from the browser.

**Describe the solution you'd like**

We should have a way to automatically create the certificates for ports 5061 (tls) and 5063 (was), ideally by using lets-encrypt.

**Describe alternatives you've considered**

We currently do this manually to secure the WebUI, by performing the following steps.

1. Extract the certificate and private key from the acme.json file generated by Traefik (ie `le.Certificates[].certificate`)
2. Decode certificate and key using `base64 -d`
3. Generate pkcs12 => `openssl pkcs12 -export -in tls.crt -inkey tls.key -out certificate.p12 -name "certificate"`
4. Convert to jks => `keytool -importkeystore -srckeystore certificate.p12 -srcstoretype pkcs12 -destkeystore api-cert.jks`
5. Copy api-cert.jks into domains-cert.jks

**Additional context**
None

**Comment by efraa** [comment]
@psanders This issue is a duplicate of [Automating the generation of Java certificates for Routr#359](https://github.com/fonoster/fonoster/issues/359)

**Comment by psanders** [comment]
Yup. Good catch. I will keep this one and close #359

**Comment by psanders** [comment]
Won't fix in v1.x / However v2.x will have support for this when running in K8s.
