### ISSUE TITLE
Allowing the projectId to be empty

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#309]
**Is your feature request related to a problem? Please describe.**

We are asking for the `projectId` for voice applications while the value is optional for DialogFlow. We should allow this value to be empty.

**Describe the solution you'd like**

Allow the value to be empty as the Engine would use the one in the configuration file if none is present.

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by BrayanMnz** [comment]
Hello @psanders, are we only supporting DialogFlow ES connection with ROX ? 

If we're also supporting CX, projectId cannot be empty since this is needed along with the agentId and the region to detect intents using DialogFlow CX.

**Comment by psanders** [comment]
@BrayanMnz 

We will have to make indicate the requirement in the UI.
