### ISSUE TITLE
Update WebUI to take environment variables from backend

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#310]
**Is your feature request related to a problem? Please describe.**

We want to take the [NEXT_PUBLIC_APP_URL](https://github.com/fonoster/webui/blob/db35144790d58d90154da045becc1b670302df75/src/mods/shared/constants/config.ts) and `NEXT_PUBLIC_SENTRY_DSN` as dynamic values instead of hardcoding during compilation.

**Describe the solution you'd like**

Take both values from the .env instead of hardcoding.

**Describe alternatives you've considered**

Keep it as it is.

**Additional context**

None

**Comment by psanders** [comment]
@efraa do we need to keep this open or is it all done?

**Comment by efraa** [comment]
@psanders was solved.
