### ISSUE TITLE
Beta test program

### ISSUE THREAD

**Issue by yossieml** [fonoster/fonoster#325]
### Discussed in https://github.com/fonoster/fonoster/discussions/209

<div type='discussions-op-text'>

<sup>Originally posted by **psanders** November  7, 2021</sup>
**Would you join us?** 

We are currently working with a small group of individuals and organizations, that want to test Fonoster before it becomes public. At the moment access to the pre-beta version of Fonoster is invited only.

If you are interested in trying Fonoster, please drop a comment below and we will guide you on how to start.

-- UPDATE ---

We are only waiting on finishing the WebUI so we can open the platform for testing :) 

https://www.loom.com/share/6a4204c12a4c4ac6b4a1e65037ad4441</div>

**Comment by psanders** [comment]
Hi @yossieml 

I am closing this issue as it provides no context. Feel free to continue the conversation at https://github.com/fonoster/fonoster/discussions/209.
