### ISSUE TITLE
The Gather verb takes too long when using a languageCode other than en-US

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#326]
**Describe the bug**

The Gather verb takes too long when using a languageCode other than `en-US`. The same happens when using alternativeLanguageCodes with a code other than `en-US,` such as Spanish.

**To Reproduce**

Use the languageCode parameter in the Gather verb like in the example bellow:

```js
const text = await res.gather({ source: "speech", alternativeLanguageCodes: ["es-US"] });
console.log(text)
```

Observe that the result takes significantly longer (about 59s) than using the default `en-US.`

**Expected behavior**

It should behave the same, regardless of the languageCode.

**Additional context**

We traced the issue to [@googleasr](https://github.com/fonoster/fonoster/tree/main/mods/googleasr). As a workaround, we can add the option `{ model: 'command_and_search' },`.

**Comment by psanders** [comment]
@efraa if we determine that this is google tts bug, we just need to mention the the issue somewhere in the Docs.

cc @YuriCodes

**Comment by efraa** [comment]
This error seems to be unrelated to GoogleTTS, tests show that the processing takes at most one second.

```typescript
const run = async () => {
  const config = {
    projectId: "PROJECT_ID",
    keyFilename: ".config/google.json",
    languageCodes: ["en-US"],
    alternativeLanguageCodes: ["es-US"],
  };
  
  const tts = new GoogleTTS(config);

  console.time("synthesize");
  const result = await tts.synthesize(
    '<speak data-ui-hide-intent="true"> <par> <media xml:id=\'a\'> <speak><break time="2s" />Hello, thanks for calling! How can I help you? </speak> </media> <media xml:id=\'bg-loop\' end="speak.begin"> <audio soundLevel="-5dB" src="https://storage.googleapis.com/gablex-tts/persona/house/bg-loop-minimal.mp3"/> </media> <media xml:id="speak" begin="a.end-500ms"><audio soundLevel="+10dB" src="https://storage.googleapis.com/gablex-tts/persona/house/slang_notification_speak_now_08.wav"/></media> </par> </speak>',
    {
      ssmlGender: "FEMALE"
    }
  );

  console.timeEnd("synthesize");

  logger.info("result", result);
};

run();
```

This snippet tests only the GoogleTTS module and its results are selected in less than a second.

![Image](https://user-images.githubusercontent.com/40646537/216192796-a6906036-d1c7-408e-b289-8fd62830bcb8.png)

**Comment by efraa** [comment]
With a mix of workaround and timeout, it works as expected.

```typescript
voiceServer.listen(async (req: VoiceRequest, res: VoiceResponse) => {
  try {
    await res.answer();

    await res.say(
      "<speak>Para español diga: español.ó,marque el número uno</speak>",
      {
        name: "es-US-Wavenet-B",
      } as any
    );

    console.time("gather");
    const languageOption = await res.gather({
      timeout: 5000,
      numDigits: 1,
      source: "dtmf,speech",
      model: "command_and_search",
      alternativeLanguageCodes: ["es-US"],
    } as any);

    console.timeEnd("gather");

    logger.info("[call]: user languageOption", { languageOption });

    await res.hangup();
  } catch (error) {
    if (
      (error as any).status !== 404 ||
      (error as any).message?.includes("code 404")
    ) {
      logger.error("[call]: error", error);
    }
  }
});
```

The results are obtained in an average of 2 to 5 seconds.

![Image](https://user-images.githubusercontent.com/40646537/216194626-6fbcefff-634f-4172-91ef-03898a8c4056.png)

**Comment by efraa** [comment]
### Workaround:

If you want to use alternative languages, you need to add the `{ model: 'command_and_search' }` parameter to the collect verb.
