### ISSUE TITLE
WhatsApp Integration

### ISSUE THREAD

**Issue by gumbarros** [fonoster/fonoster#329]
**Is your feature request related to a problem? Please describe.**
I'm dependent on using Twilio because of the WhatsApp API integration.

**Describe the solution you'd like**
A WhatsApp integration to fonoster, like the Twilio one.

**Describe alternatives you've considered**
Twilio.

**Additional context**
It will be good to have a FOSS WhatsApp API alternative.

**Comment by psanders** [comment]
@gumbarros 

I can see how this could be useful. We left this feature out of the [roadmap](https://github.com/orgs/fonoster/projects/9) to focus on things we can implement in a reasonable time.

Do you care to repost this as a [discussion](https://github.com/fonoster/fonoster/discussions)? I will talk to my network and see if we have anyone experienced in this area and least bring this to the roadmap.

**Comment by gumbarros** [comment]
Hello @psanders , thanks for the feedback. Created the [discussion](https://github.com/fonoster/fonoster/discussions/332).
