### ISSUE TITLE
Use cache files instead of regenerating tts

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#333]
**Is your feature request related to a problem? Please describe.**

Fonoster Voice could benefit from re-using the files generated by a TTS Engine. It will make things faster and reduce costs for the users.

**Describe the solution you'd like**

The Voice server could maintain a list (perhaps in memory). The list should be a hash of the parameters used to create the transcriptions. 

Also, consider storing the following information to be able to filter out aged entries.

```json
{
 "path": "/etc/tts/618572e3ec11d10600000001.wav",
 "format": "wav",
 "ttl": "24h",
 "createAt": 1651601950221 
}
```

After that, all that is left is to check every request by the `Say` verb and serve the file from the disk.

**Describe alternatives you've considered**

No.

**Additional context**

Related feature: https://github.com/fonoster/fonoster/issues/260

**Comment by xquanluu** [comment]
Hi @psanders Can we just simple check if the file already exist and reuse it. otherwise we do synthesize.
The file retention can be managed by external cronjob that check if the age of the file is already expired and delete it.

My think is in google TTS:

      if (!fs.existsSync(pathToFile)) {
        logger.verbose(
            `@fonoster/tts.GoogleTTS.synthesize [input: ${text}, isSSML=${isSSML(
                text
            )} options: ${JSON.stringify(options)}]`
        );

      const voice = merge(defaultVoice, options || {});
      const input = isSSML(text) ? { ssml: text } : { text: text };

      const request = {
        voice,
        input,
        audioConfig: { audioEncoding: "LINEAR16" }
      };

      // Performs the text-to-speech request
      const [response] = await client.synthesizeSpeech(request as any);
      // Write the binary audio content to a local file
      const writeFile = util.promisify(fs.writeFile);
      await writeFile(pathToFile, response.audioContent, "binary");
    }
    return { filename, pathToFile };

**Comment by psanders** [comment]
My preference would have been to set this at a lower level so future tts plugins would take care of this instead of individual implementations. My initial though was to create an abstract class and the synthesize method abstract too. 

Give me a few days to meditate on this.

Either way, if its cool I will assign this issue to you.

**Comment by efraa** [comment]
Solved on https://github.com/fonoster/fonoster/pull/448
