### ISSUE TITLE
The OAuth2 workflow fails if the GH user doesn't have a name

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#355]
**Describe the bug**

The account creation and authentication fails, if the GitHub user doesn't have a name.

**To Reproduce**

1. Go to your GitHub account settings the name 
2. Then, attempt to create an account on Fonoster Cloud
3. See the error on your browser

**Expected behavior**

It should use a placeholder and allow the user to continue.

**Screenshots**

Screenshot showing a working and failing account.

![Missing Name](https://user-images.githubusercontent.com/539774/171953450-03cbdace-4c83-4abe-95fe-5e40c34e3aed.png)

**System information (please complete the following):**

Tested on several browsers for confirmation.

**Additional context**

The issue is that the Users API expects a name in the [CreateUserRequest](https://github.com/fonoster/fonoster/blob/68d8d7060d6b74908e25834e03da2df78b8a9dec/mods/users/src/client/users.ts#L112) type.

**Comment by psanders** [comment]
Update.

As a consequence of this issue, we will also need the ability to update the User's name from the UI.

**Comment by efraa** [comment]
https://github.com/fonoster/webui/commit/710cae93343d448610b756938697cd412c454945

**Comment by psanders** [comment]
Thanks. Approved.
