### ISSUE TITLE
The verb Play fails without feedback to the user

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#364]
**Describe the bug**

The verb `Play` fails without feedback to the user.

**To Reproduce**

1. Create a voice application and use the `Play` verb
2. Pass the string `https://storage.googleapis.com/fn01/sounds/beep.sln16` as a parameter
3. Attempt to connect with the voice application
4. Notice how the app fails without any notification

**Expected behavior**

The user should receive a notification of the error. Additionally, we could provide client-side validation.

**Screenshots**

![Failed Sound Feedback](https://user-images.githubusercontent.com/539774/172026342-b6718c1e-abac-4a72-b540-57cf21e8f665.png)

**System information (please complete the following):**

NA

**Additional context**

NA

**Comment by xquanluu** [comment]
Hi @psanders 
I want to work on this issue.

I understand that fonoster is just a HTTP  client/server to control a SIp server deployed somewhere which is handling the call. Can you give me some hint:
1/ How fonoster send a notification for the error? I guess this is from Sip Server behavior and not from fonoster itself.
2/ about client-side validation, The playVerb itself should check/download the file and check the quality of the audio, is that what you means?

If you have any hint to me, I would help me a lot.

Thanks

**Comment by psanders** [comment]
@xquanluu 

For sure. I'm co-assigning this to you. I will create some notes around this issue, so we can start collaborating.

Thanks for all your help 🙏

**Comment by psanders** [comment]
@xquanluu I'm still looking into this. I hope to have a way forward by the end of this week. 

By the way, I would be super cool if you joined the [Discord community](https://discord.gg/mpWSRUhG7e). We wanted to publicly thank you, but realize you are not there yet :) 

(But if it's not your thing, there is no worries)

**Comment by xquanluu** [comment]
Thanks @psanders I'm already there with different name. it's ok, just a small PR.

I really want to contribute on this project or routr or whatever, If something I can code/share workload with your team please let me know.

**Comment by xquanluu** [comment]
Hi @psanders just waiting to contribute on this, please let me know if there is something I can contribute here, or if you have any other good first issue, please let me know.

**Comment by psanders** [comment]
@xquanluu I have this on my todo, but it might be a few days before I get to it. Besides, I was wonder if you could dm at Discord. We are trying to have a release of Routr as soon as possible, and wonder if you would be interested in joining the effort.

**Comment by xquanluu** [comment]
Yes, @psanders  I'm interested in routr as well. I changed the name on discord to xquanluu, you can ping me there please.

**Comment by xquanluu** [comment]
Hi @psanders after check this: https://issues.asterisk.org/jira/browse/ASTERISK-26661
The asterisk does not support error handling yet.

So my plan is to create a timeout from PlaybackStarted event, the timeout will be clear if PlaybackFinished even happens, if timeout happens, we raise notification to application, I will try to create a small PR for this if you think that's good idea

**Comment by xquanluu** [comment]
hmm. my bad, we cannot know the duration of the audio to detect PlayBackFailed

**Comment by psanders** [comment]
> hmm. my bad, we cannot know the duration of the audio to detect PlayBackFailed

I was thinking maybe we can capture the error from Stasis.
