### ISSUE TITLE
Add stop command for docker.

### ISSUE THREAD

**Issue by alifiratari** [fonoster/fonoster#382]
**Is your feature request related to a problem? Please describe.**
There is no stop command for docker operator.

**Describe the solution you'd like**
Added stop command for docker.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by psanders** [comment]
@alifiratari 

Your [PR](https://github.com/fonoster/fonoster/pull/383) was merged. I am closing this issue as completed. 

Again, thanks for the PR.
