### ISSUE TITLE
The test phone @ WebUI is using hardcoded values

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#401]
**Describe the bug**

The test phone is pointing at hardcoded values.

**To Reproduce**

Go to the [source code](https://github.com/fonoster/webui/blob/1b5d81bb21259c9312049970a82d44b694a8b80c/src/mods/numbers/screens/board/NumbersBoard.tsx#L41), and observe the values of the constructor.

**Expected behavior**

We need to add environment variables to accept the Domain and Server. I propose we create the following environment vars:

`TEST_PHONE_DOMAIN`
`TEST_PHONE_SERVER`
`TEST_PHONE_USERNAME`
`TEST_PHONE_SECRET`
`TEST_PHONE_DISPLAYNAME`

**Screenshots**

NA

**System information (please complete the following):**

NA

**Additional context**
NA

**Comment by BrayanMnz** [comment]
Environment vars will limit these to "the container" if I want to connect my instance to a new server/domain 
I'll need to rebuild everything from scratch. 

this not will be a limitant ?

**Comment by psanders** [comment]
The environment variables will be read at runtime.

**Comment by efraa** [comment]
https://github.com/fonoster/webui/commit/26d53c4070ffe9474b5850c8c0b9684e939e0b97 @psanders

**Comment by psanders** [comment]
Looks good to me.
