### ISSUE TITLE
Create Rox demo application (rox-ui)

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#404]
### Summary

A demo application of Rox (`rox-ui`), able to be deployed as a simple web application.

### Intended Outcome

We can run the application directly from its repository using CodeSpace or GitPod. If neither option is possible, we should be able to deploy in a local environment.

> Ideally, we use CodeSpace.

### How will it work?

We click the CodeSpace/GitPod button on `rox-ui` repository and open a page that hosts the application. We then update the environment variables to point to the corresponding environment.

### Overview:

NA

### Requirements:

- [x] The application works properly in a local environment
- [x] The application works properly when launched using CodeSpace or GitPod
- [x] The application accepts parameters to connect to Fonoster

**Comment by psanders** [comment]
@efraa The events server is now sending events properly. However, Rox UI is not showing the cards. Instead, it shows a "Permissions" message.

**Comment by psanders** [comment]
Let's make the task the priority, so we can close the ticket.

**Comment by efraa** [comment]
Done, you can launch the app using GitPod. @psanders 

<a href="https://gitpod.io/#https://github.com/fonoster/rox-ui">
  <img
    src="https://img.shields.io/badge/Contribute%20with-Gitpod-908a85?logo=gitpod"
    alt="Contribute with Gitpod"
  />
</a>

**Comment by psanders** [comment]
Thanks for everything. I am closing this ticket.
