### ISSUE TITLE
Create the pricing page

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#408]
### Summary

Create the pricing page for Fonoster's website.

### Intended Outcome

The page is created and deployed along with the main website.

### How will it work?

NA

### Overview:

Please see this [notion page](https://www.notion.so/Pricing-Page-Draft-cc97b3cf0b774a388995b7033fed7302) with the copy for the page.

### Requirements

NA

**Comment by psanders** [comment]
@efraa I saw the new branch. Everything looks great. 

Can you merge all the changes into master and clean up older branches?

After that, feel free to close this ticket.

**Comment by efraa** [comment]
@psanders  sure 👍
