### ISSUE TITLE
Fix health check on all API containers

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#409]
### Summary

Fix health check on all API services under [fonoster.](https://github.com/fonoster/fonoster)

The checks on all modules were disabled at some point this year due to incompatibility between `@grpc/grpc-js` and `grpc-ts-health-check`. 

Notes:

- It seems that the latest version has been updated to support `@grpc/grpc-js`.
- Here is some information about gRPC and health checks https://github.com/grpc/grpc/blob/master/doc/health-checking.md
- Every service has a `healthcheck.ts` file to take care of the health check. See [example](https://github.com/fonoster/fonoster/blob/0.3/mods/agents/src/service/healthcheck.ts).

### Intended Outcome

All gRPC and non-gRPC modules implement health checks.

### Requirements

We must fix checks in the following modules.

- [x] Agents
- [x] Apps
- [x] Auth
- [x] Callmanager
- [x] Domains
- [x] Funcs
- [x] Limiter
- [x] Monitor
- [x] Numbers
- [x] Projects
- [x] Providers
- [x] Secrets
- [x] Storage
- [x] Users
- [x] Voice (non gRPC service)

**Comment by psanders** [comment]
@efraa 

I saw you created a cloned and cleaned the `grpc-ts-health-check` packages. 

I renamed the project to `grpc-health-check`.

Can we update the package name to `@fonoster/grpc-health-check`.

Also, we need to reference the original authors somewhere in the README.

**Comment by efraa** [comment]
Sure, working on it. @psanders

**Comment by efraa** [comment]
Related repo: [@fonoster/grpc-health-check](https://github.com/fonoster/grpc-health-check)

**Comment by psanders** [comment]
Reminder to myself. Look into this PR -> https://github.com/fonoster/fonoster/pull/419

**Comment by psanders** [comment]
I check the PR, and everything looks great. Can you try the [last build](https://hub.docker.com/repository/docker/fonoster/limiter/tags?page=1&ordering=last_updated) at `staging`?

**Comment by efraa** [comment]
This is working now! 🚀 @psanders

**Comment by psanders** [comment]
@efraa Thanks a lot. Closing it!
