### ISSUE TITLE
Fix telemetry on all API containers

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#410]
### Summary

Fix telemetry on all services.

### Intended Outcome

We can visualize telemetry using Jaeger.

### Requirements

- [x] All services implement OpenTelemetry auto instrumentation to track all requests (gRPC and Rest). 
- [x] Custom Events, Tracers, and Spans are fixed.

**Comment by efraa** [comment]
Related issue: https://github.com/jaegertracing/jaeger/issues/2172

**Comment by psanders** [comment]
@efraa 

Thanks for the reference. We have to triage this. If I remember correctly, this only happens when deployed a container. It did not happen in my local environment.

**Comment by efraa** [comment]
Fixed @psanders
