### ISSUE TITLE
Add parameter enableEvents to WebUI/Apps and CTL/Apps

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#411]
### Summary

Add the field `enableEvents` to WebUI/Apps and CTL/Apps since both tools are missing the field.

### Intended Outcome

We can configure Apps to support events. 

> Apps meant to be used by Rox-UI require this feature to work as expected.

### Requirements

- [x] Add the field to both the WebUI/Apps and CTL/Apps
- [x] Update Rox to accept the field. Please see [file](https://github.com/fonoster/rox/blob/9fb0d8a4f8e3cd521c8c798513cdff0227198fc1/src/voice.ts#L132)

**Comment by efraa** [comment]
@psanders 

- https://github.com/fonoster/webui/pull/10
- https://github.com/fonoster/rox/pull/5
- https://github.com/fonoster/fonoster/pull/415

**Comment by psanders** [comment]
@efraa 

Did you get the chance to deploy this to the staging server?

**Comment by efraa** [comment]
@psanders 

Check -> https://github.com/fonoster/fonoster/pull/418

**Comment by psanders** [comment]
All done.
