### ISSUE TITLE
Improve onboarding experience for contributors

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#412]
### Summary

We create an onboarding process for code and non-code contributions. Since we have ~45 repositories, I believe we should centralize contributions documents on a repository.

This will be a living document; we don't need to get right on the first shot. Instead, we can create the documents and improve them over time.

### Expected Outcome

We are prepared to receive code and non-code contributions on our priority repositories.

### Requirements

- [ ] We create an onboarding process for both code and non-code contributions
- [ ] The document should state which repositories are ready to accept contributions
- [ ] Whenever possible, we use GitPod to make it easy for newcomers to try a given repository
- [ ] The onboarding should allow a one-time contribution
- [ ] Repositories should have well-documented `good-first-issue`
- [ ] We should find ways to recognize contributions via all possible channels
- [ ] Repositories might have their additional contribution notes when necessary

### Ideas to borrow from

- https://github.com/EddieHubCommunity
- https://docs.naas.ai/contributing-to-naas/contributing
- https://glossary.cncf.io/
- https://glossary.cncf.io/contribute/
- https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/CONTRIBUTING.md
- https://ngrx.io/contributing
- https://rasa.com/community/contribute/

**Comment by BrayanMnz** [comment]
Adding the Apache Sling contribute guide as an additional reference
https://github.com/apache/sling-org-apache-sling-engine/blob/master/CONTRIBUTING.md
https://sling.apache.org/contributing.html

**Comment by luzpaz** [comment]
Any progress on this ?

**Comment by elidakirigo** [comment]
I'm open to adding on my skills as well

**Comment by psanders** [comment]
@luzpaz @elidakirigo 

Sorry for the very late response. And no, no much progress on this ticket. Maybe we should collab on it.
