### ISSUE TITLE
BACKERS.md link not working in README

### ISSUE THREAD

**Issue by ykdojo** [fonoster/fonoster#413]
Looks like it's not correctly linking to the right URL.

**Comment by shraddhafalane** [comment]
Would like to take this up

**Comment by prajnao** [comment]
hey @psanders , I would like to work on this issue.

**Comment by psanders** [comment]
@Prajnaprabhu3 👋

Sounds good. I will add some information about this ticket sometime soon.

**Comment by prajnao** [comment]
yeah sure, let me know the correct URL that needs to be linked

**Comment by psanders** [comment]
@Prajnaprabhu3 

We want this to point to the [sponsors](https://github.com/sponsors/fonoster) link.

**Comment by prajnao** [comment]
yeah sure, I'll make the changes. And raise a PR

**Comment by iamppborah** [comment]
Hey @Prajnaprabhu3, are you still working on this ?

**Comment by iamppborah** [comment]
Hey @psanders, I would like to work on this

**Comment by psanders** [comment]
@ppborah 

Please take it, and let me know if you need any help.

**Comment by iamppborah** [comment]
![Fonoster](https://user-images.githubusercontent.com/96339995/190062469-a4de533a-c919-49c4-b8ad-29edbca5d85a.png)

Hey @psanders, these two links are different: **first one** links to https://github.com/sponsors/psanders and **second one** links to https://github.com/fonoster/fonoster

Do you want me to keep both ?

**Comment by psanders** [comment]
Good catch. We no longer need the sponsors/psanders.

**Comment by RohitRajvaidya5** [comment]
Is this issue close or resolved?

**Comment by iamppborah** [comment]
Hey @RohitRajvaidya5, feel free to review my PR :)
