### ISSUE TITLE
Some of the links on the website are not working

### ISSUE THREAD

**Issue by ykdojo** [fonoster/fonoster#414]
**Describe the bug**
I noticed that the blog link and the pricing link in particular go to 404

**Comment by efraa** [comment]
@ykdojo 

Thanks for reporting the issue. We triaging this and confirm it as a bug. We are currently testing a fix for this.

**Comment by efraa** [comment]
@ykdojo 

Thanks for reporting the issue, we've fixed it and you can check again.
