### ISSUE TITLE
Project creation is very slow (takes up to 5 min)

### ISSUE THREAD

**Issue by alpenp** [fonoster/fonoster#428]
**Describe the bug**

Sign in with github failing - Green spinning circle no account created/no response. (Update: It took about 3-5 min; by the time I finished this bug report it finished)

**To Reproduce**
1. Go to  https://learn.fonoster.com/docs/getting_started/create_an_user_account
2. Go to the link at "  You will need to Sign In with GitHub to create a Fonoster account."
3. Then, "Authorise in Github"
4. There is the spinning green circle
5. It takes close to 2 min - not clear what is happening.
6. Luckily  I waited, then I got "Your Project name" 
7. Then type a name and click "Create Project" - This took close to 5 min. At that time it is not clear what todo. Green circle spinning

**Expected behavior**

Quicker
Or
Just inform user that "The project NAME is being created. This may take up few minutes. You may navigate away from this page - the project will be created in the background"

 
**System information (please complete the following):**
 - OS:  Browser/ChromeOS
 - NodeJS, NPM versions - N.A
 - CTL version [e.g. 0.1 ] - N.A

**Additional context**

May be look at the UI for gitlab or github import a repo. It does it asynchronously. 

Thanks for your great work!

**Comment by YuriCodes** [comment]
Hello @alpenp and thank you for reaching out! We were having the same issues but they should be fixed by now. Would you mind trying again?

**Comment by alpenp** [comment]
Yes it is quicker now. Thanks
