### ISSUE TITLE
Help identify the current project on the CLI

### ISSUE THREAD

**Issue by YuriCodes** [fonoster/fonoster#445]
At the moment there is no way to tell which project is set to be the default on the CLI.
It would be nice to have an indicator so we know which one is the "default". We could mark the default project with an ```*```.

For example:

```
$ fonoster projects:ls
Ref / Access Key Id           Name        
PJ619154d081467a0700000001    Acme Corps *
PJ879134d081567g0h00000001   Walmart North
```

**Comment by xquanluu** [comment]
Hi @YuriCodes  Can I contribute on this issue? I will provide PR soon

**Comment by YuriCodes** [comment]
Awesome! Go ahead

**Comment by psanders** [comment]
Closing this [as solve](https://github.com/fonoster/fonoster/pull/447).
