### ISSUE TITLE
Unable to originate call with the CallManager

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#449]
**Describe the bug**

A user reported being unable to make a call while using the CallManager. Also, the error display at Fonoster/Console needs to be more descriptive to yield the reason for failure.

**To Reproduce**

This issue can be reproduced by attempting to initiate a call using the CallManager and observing the error alert at console.fonoster.io.

**Expected behavior**

The call should be initiated, and a clear error clearly stating the issue should be displayed in case of a call failure.

**Screenshots**

![image](https://user-images.githubusercontent.com/539774/205352963-3c09e644-90f4-4c5a-9b04-06a1f8f66319.png)

**Additional context**

It's becoming evident that we need to find a better way for users to add new Numbers. At a minimum, users should be able to test connectivity to a trunk and test outbound directly from the browser.

**Comment by psanders** [comment]
@efraa 

We need to make several updates to the API, CTL, and Web Application:

- [x] No change needed in the [proto](https://github.com/fonoster/fonoster/tree/main/mods/numbers/src/protos) definition
- [x] Update API to enforce E.164
- [x] Remove [ignoreE164Validation](https://github.com/fonoster/fonoster/blob/main/mods/callmanager/src/client/callmanager.ts) flag from the CallManager service
- [x] Update WebApp to enforce E.164
- [x] Update CTL to enforce E.164
- [x] Update API examples to include `+` sign

Related work at [fix/normalizing-numbers-as-e164](https://github.com/fonoster/routr/compare/main...fix/normalizing-numbers-as-e164)


![Image](https://user-images.githubusercontent.com/539774/206864648-607b8ef0-5fa0-4368-95ac-b3086e8262a9.png)

**Comment by psanders** [comment]
Video explainer: https://www.loom.com/share/a9ff7d19810145ac84b07e420b5a4f98

**Comment by xquanluu** [comment]
Hi @psanders 

from your video, I started to contribute on this: Update API to enforce E.164 and Remove [ignoreE164Validation] flag from the CallManager service
I raised a PR link so we can coordinate together and you can help me to review sooner.

I start to take a look at Update WebApp to enforce E.164

**Comment by psanders** [comment]
@efraa this is pretty close to done. We still need to validate the input for the ctl, but we can fix that next week.

**Comment by xquanluu** [comment]
Hi @psanders 
About the task Update CTL to enforce E.164, I see that with previous commit the CTL will validate the input from user and enforce E.164

Can you please help to identify what we need to do? Bellow is the result when I run the CTL:

git:(main) ✗ ./run numbers:create
This utility will help you create a new Fonoster Number
Press ^C at any time to quit.
(node:91743) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
? number in E.164 format (e.g. +16471234567) 414124
? service provider TX_DEV
? address of record sip:abc@abc.com
? ready? Yes
Creating Number 414124... done
 ›   Error: 3 INVALID_ARGUMENT: e164Number field must be a valid e164 value.

**Comment by psanders** [comment]
@xquanluu Got catch! I missed the fact that this is being validated by the backend. 

We are all set here. Thanks.
