### ISSUE TITLE
PR template not showing for new PRs

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#468]
Fix PR template not showing for new PRs.

**Comment by techwithbhavya** [comment]
Hey @psanders , I would like to work on this issue. Can you please assign this to me?

**Comment by psanders** [comment]
@bhavyastar welcome to the party 🥳

**Comment by harshmange44** [comment]
@bhavyastar Hey can I work on this issue since you haven't fixed this yet?
CC: @psanders

**Comment by techwithbhavya** [comment]
This is done. Busy with exams. Just will make PR by today .
