### ISSUE TITLE
Docker installation not working

### ISSUE THREAD

**Issue by cogmeta** [fonoster/fonoster#479]
**Describe the bug**
Docker installation is not working as expected. fonoster/mediaserver is stuck in starting stage.
sudo docker logs 67ce8618c738
[INFO  tini (1)] Spawned child process '/run.sh' with pid '7'
Unable to open specified master config file '/etc/asterisk/asterisk.conf', using built-in defaults
Waiting for localhost:8088.
Connected!
[
  'This API is using a deprecated version of Swagger!  Please see http://github.com/wordnik/swagger-core/wiki for more info'
]
[INFO  tini (1)] Main child exited with signal (with signal 'Terminated')
[INFO  tini (1)] Spawned child process '/run.sh' with pid '7'
Unable to open specified master config file '/etc/asterisk/asterisk.conf', using built-in defaults
Waiting for localhost:8088.
Connected!

**Comment by psanders** [comment]
Closing in favor of #430
