### ISSUE TITLE
Nigeria E.164 Landline Numbers Error

### ISSUE THREAD

**Issue by salami-dev** [fonoster/fonoster#483]
**Describe the bug**
Trying to create a Nigerian E.164 Landline number on the [Fonoster Console](https://console.fonoster.io/) throws this error "Invalid phone number, please enter a valid phone number with E.164 format (e.g. +17853178070)"

**To Reproduce**
1. Go to 'https://console.fonoster.io/network/numbers'
2. Click on the '+' button
3. Select Phone Numbers
4. In the 'E.164 Number' field, select country as Nigeria (+234)
5. Type '12802500' after the +234 Prefix
6. See error
7. Try to bypass form validation
8. Submit number to API
9. See error

**Expected behavior**
Should be able to add a Nigerian E.164 Landline Number to Phone Numbers 

**Screenshots**
![image](https://user-images.githubusercontent.com/57477131/216804753-96236862-e7d9-4ab2-b75e-e9541ad41af5.png)

**System information (please complete the following):**
 - Chrome Browser on Windows

**Comment by YSternlicht** [comment]
Had same issue when trying from UK. Number was similar to +447761444669

**Comment by psanders** [comment]
@efraa any ideas about this issue?

**Comment by oracle-of-me** [comment]
We had the same issue. The problem is the generated request. 

![grafik](https://user-images.githubusercontent.com/94798337/227151392-7d40aa9a-428c-461d-9e0f-7f01cd10536f.png)

When you look at the request send, its seems to miss the "+" sign. When you add it manually and resend the request you can add numbers. 

![grafik](https://user-images.githubusercontent.com/94798337/227151943-085c13f8-5215-4461-9725-e50413337f8e.png)

**Comment by efraa** [comment]
Hi @salami-dev,

Thanks for taking the time to try Fonoster. I will be evaluating this issue and will give updates on it no later than next Monday.

**Comment by efraa** [comment]
Hi @salami-dev,

We found part of the problem and it comes from the library we are using to validate the numbers, it seems that Nigerian numbers are up to 11 digits long but the lib assumes they should be 10 digits.

Check: https://github.com/AfterShip/phone/blob/master/src/data/country_phone_data.ts#L1266

We will open an issue for this and next week we will patch the node_modules if necessary.

**Comment by efraa** [comment]
Follow https://github.com/AfterShip/phone/issues/349

**Comment by salami-dev** [comment]
Hi @efraa 

Thanks for diagnosing the issue. 

Nigerian mobile numbers are 11 digits long. 

Landlines are generally 8 - 9 digits, ex: 012802500

**Comment by psanders** [comment]
@salami-dev 

We added support for Nigerian phone numbers.

Would you test configuring your number and let us know?

**Comment by salami-dev** [comment]
Hi @psanders 

Still unable to add from the fonoster console.

![image](https://user-images.githubusercontent.com/57477131/229375327-9587927b-1e64-4be2-93e6-bcf9ded3ebac.png)
![image](https://user-images.githubusercontent.com/57477131/229375359-0128c64a-5cd0-4638-b0a4-97f765286c9d.png)

**Comment by luzpaz** [comment]
Any updates?

**Comment by MRakox** [comment]
Same issue with French numbers (starting with +33), except I'm able to add them on the dashboard but they don't work with the node SDK.

Further informations :
I'm trying to make outbound calls with the SDK but I'm getting an error saying the "from" value isn't a valid e164 number (but it's the exact same as the one registered on the dashboard)

**Comment by psanders** [comment]
@MRakox, thank you for reporting this issue. I will work on finding a solution as soon as I am able to allocate some time for it.
