### ISSUE TITLE
Trouble setting up a SIP Trunk

### ISSUE THREAD

**Issue by oracle-of-me** [fonoster/fonoster#486]
Hello everyone,

we are having problems setting up the SIP Trunk for Fonoster. I want to add www.fonial.de as an SIP Trunk and did all the setup there. I got the SIP Username and password.
When I add them in Fonoster it looks like it's working, but its not. On the Fonial website, it says there is no connection. There are no error codes in neither Fonoster nor Fonial, so I don't know what to do next. 
The SIP Trunk works fine on other applications.

I added Screenshots of Fonoster and Fonial. 

![image2](https://user-images.githubusercontent.com/94798337/222661921-bcc94965-e8e4-4ae5-8214-a7eb4d3a791c.png)
![image](https://user-images.githubusercontent.com/94798337/222661930-b959231a-1393-4d7f-b38f-b7151753f58e.png)

**Comment by psanders** [comment]
Hello! As we communicated on Discord, there were some issues with the dynamic registration feature, and as a result, it has been temporarily disabled. However, there's an alternative solution that you can implement. You can configure your provider to use static registration and whitelist Fonoster's IP address, which is 157.245.118.236. This should resolve the issue and allow you to continue using Fonoster's services.
