### ISSUE TITLE
Experimental Functions document  missing

### ISSUE THREAD

**Issue by dovidgef** [fonoster/fonoster#489]
In the [Deploy your server](https://github.com/fonoster/fonoster/blob/main/docs/operator/deploy-your-server.md) document there is a link to [Adding support for Cloud Functions (Experimental)](https://github.com/fonoster/fonoster/blob/main/docs/operator/adding_support_for_functions.md) 

It appears that this document is missing

**Comment by psanders** [comment]
Good catch. We are not actively working on support for functions, and I removed the link to avoid confusion.

**Comment by dovidgef** [comment]
Thanks, would be nice if there was some way to run a PBX serverless like via Cloudflare Workers
