### ISSUE TITLE
What are the correct way to configure external SIP to send call to Fonoster

### ISSUE THREAD

**Issue by jBernavaPrah** [fonoster/fonoster#493]
Hi Fonosterster! 

I'm trying to replicate the inbound functionality that I already have with Vonage (with Programmable Voice) using DIDWW (as SIP), but I'm blocked on the first part of the integration. How can I configure DIDWW in order to let them send the call to Fonester?

What seems to me more similar to [this api](https://developer.vonage.com/en/voice/voice-api/guides/programmable-sip) are Fonoster domains. Am I in the correct supposition here?

May you point me to where in the documentation I can find more explanation?

Thanks!
JBP

**Comment by psanders** [comment]
Hi JBP,

I hope you're doing well today! Thank you for reaching out to us. I understand that you're looking for information on Trunks and Fonoster. I'm happy to help with that.

Regarding the information in your message, I'd like to make a few corrections for clarity and accuracy. Fonoster supports static registration and user/password authentication for Trunks. To set this up, you'll need to whitelist Fonoster with your provider using our IP address `157.245.118.236`. Then, you can create a new Trunk and related Number on Fonoster.

As a friendly reminder, GitHub Issues is intended for tracking bugs and feature requests. If you have any further questions or would like to continue the conversation, please feel free to use [GitHub Discussions](https://github.com/orgs/fonoster/discussions). Also, we hold office hours every Wednesday at [Discord](https://discord.gg/mpWSRUhG7e) and I'd be happy to demo the Trunks and Fonoster setup for you during our next session.

Looking forward to speaking with you soon!
