### ISSUE TITLE
Excessive repetition of transfer message during call transfer process

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#495]
**Describe the bug**

When performing a call transfer, the transfer message is repeated too many times, leading to a poor customer experience.

**To Reproduce**

1. Initiate a call transfer.
2. Listen for the transfer message.
3. Notice that the transfer message is repeated too many times, leading to a poor customer experience.

**Expected behavior**

The transfer message should only be played once during the call transfer process.

**Screenshots**

NA.

**Actual result**

The transfer message is repeated too many times, causing a poor customer experience.

**Comment by luzpaz** [comment]
Any traction on this ticket ?

**Comment by psanders** [comment]
I haven't had much time lately.
