### ISSUE TITLE
Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [fonoster/fonoster#557]
**Describe the bug**
Twitter logo is updated recently and hasnt been updated on the site. I didnt find any issue related to this.

**To Reproduce**
Scroll to footer section and see twitter old logo

**Expected behavior**
Twitter logo should be changed to X

**Screenshots**
<img width="960" alt="Screenshot 2023-09-10 085858" src="https://github.com/fonoster/fonoster/assets/91591901/8e9a18b7-ae18-4260-ab6a-f69d19e257a3">

**System information (please complete the following):**
 - OS: [e.g. Linux]
 - NodeJS, NPM versions [e.g. v14.16.0, 7.10.0]
 - CTL version [e.g. 0.1 ]

**Additional context**
@psanders 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

**Comment by psanders** [comment]
Absolutely, take it away @lalitkumawat1m!

**Comment by lalitkumawat1m** [comment]
this issue is related to fonoster website
and I have created pr in fonoster website repo regarding this issue

**Comment by psanders** [comment]
Closing. Fixed by PR https://github.com/fonoster/fonoster/pull/624
