### ISSUE TITLE
The test call does not connect

### ISSUE THREAD

**Issue by yuvalkry** [fonoster/fonoster#558]
**Describe the bug**
The test call does not connect to the web hook.
It worked a few days ago.

**To Reproduce**
As described in https://learn.fonoster.com/docs/getting_started/make_a_hello_world

**Expected behavior**
An indication of incoming call in the ngrok console and the node service

**System information (please complete the following):**
 - OS: Linux
 - NodeJS, NPM version 18.16
 

**Additional context**

**Comment by psanders** [comment]
@yuvalkry, we had issues with the platform this morning, but they have since been resolved. Please try again and report if you have any additional issues.
