### ISSUE TITLE
Specification for playing wav files

### ISSUE THREAD

**Issue by yuvalkry** [fonoster/fonoster#560]
Hello,

  How to specify the audio to VoiceResponse.play()  and what should be the properties of a "wav" file?
  
   I have tried with specifying the URL, it worked only when the sampling rate of the wav file was 8k (which makes sense for telephony).
  I have tried pointing to the same file as a "file://" entry but it did not work.

  Also, it is mandatory to prefix the reference with "sound:" .

  These and perhaps other specifications should be written in the documentation.

    Thanks!

**Comment by psanders** [comment]
Would you say the main question is, "Which audio profiles does Fonoster support?"

Or do you feel that you found a bug?

**Comment by yuvalkry** [comment]
I would like to response with a WAV file. Is that possible? how?
And if not, which audio formats are valid for responding, and how to specify them to VoiceResponse.play() 
Thank you!

**Comment by psanders** [comment]
We currently support `sln16`. For an example, please check the sounds directory [here.](https://github.com/fonoster/nodejs-voiceapp) Few folks have been asking about this, so I might try to add support for mp3, and wav soon.

**Comment by yuvalkry** [comment]
Thank you,

I've read that sln16 is simply raw PCM with 16KHz sample rate.
So it would be good to either
- add a note to convert audio files to this format, for example
  ffmpeg -i audio.wav -acodec pcm_s16le -f s16le -ar 16000 -c 1 audio.sln16
- support these formats
