### ISSUE TITLE
Docker Installation Not Working

### ISSUE THREAD

**Issue by ddlidded** [fonoster/fonoster#597]
When trying to follow these exact steps:

mkdir fonoster
cd fonoster
curl -o .env https://raw.githubusercontent.com/fonoster/fonos/main/.env.example
curl -o ./compose.yaml https://raw.githubusercontent.com/fonoster/fonoster/main/compose.yaml
docker compose up -d

Results in: 
<img width="1053" alt="Screenshot 2024-01-05 at 2 41 25 PM" src="https://github.com/fonoster/fonoster/assets/63270906/79b5992c-38f7-4c34-b278-55ca70419765">

Is this a problem with the docker composer file?

**Comment by psanders** [comment]
You likely have some other process using port `8080`.
