### ISSUE TITLE
Login and Signup broken

### ISSUE THREAD

**Issue by re-masashi** [fonoster/fonoster#613]
**console.fonoster.io returns 404**

**To Reproduce**
1. send a GET request to console.fonoster.io
4. See a 404

**Expected behavior**
Signup redirect

**Screenshots**
![image](https://github.com/fonoster/fonoster/assets/68556185/5801e904-1bc5-4575-84cb-01c6809e2b3b)

**System information (please complete the following):**
 - OS: [e.g. Arch Linux]
 - Browser: Firefox

**Comment by psanders** [comment]
Thanks for the notification. The issue has been resolved.

**Comment by re-masashi** [comment]
thanks a lot for your quick response and resolution of this issue.
