### ISSUE TITLE
14 UNAVAILABLE:  Name resolution failed for target dns:app.fonoster.io Accessing endpoint app.fonoster.io... Invalid credentials or endpoint

### ISSUE THREAD

**Issue by realaidynamics** [fonoster/fonoster#615]
![fonosterendpointerror](https://github.com/fonoster/fonoster/assets/161885127/62f7917c-bd89-4dd3-810b-5a2ff5bcdb91)

https://fonoster.com/docs/getting_started/install_and_setup_the_cli
setup everything else fine and now im stuck on this, any help will be appreciated.

**Comment by realaidynamics** [comment]
new issue, seemed i had the wrong node version
![image](https://github.com/fonoster/fonoster/assets/161885127/ff7b98f4-05fc-42d5-8688-ef6c0557998e)
so i updated it and now im getting this error:
![image](https://github.com/fonoster/fonoster/assets/161885127/24afa8a4-0f80-445e-9c6c-74f4383d4f81)
and when i just ignore it and go to next step it says this:
![image](https://github.com/fonoster/fonoster/assets/161885127/5c54a106-7c37-4db1-9216-5e64df1446a1)

**Comment by psanders** [comment]
When did you create your Fonoster account? We're currently having issues with accounts that are over a year old due to expired credentials. Could that be the case for you?

**Comment by realaidynamics** [comment]
> When did you create your Fonoster account? We're currently having issues with accounts that are over a year old due to expired credentials. Could that be the case for you?

no this account is new

**Comment by psanders** [comment]
This issue has been fixed in the later versions of Fonoster.
