### ISSUE TITLE
Unable to access console.fonoster.io after login with github

### ISSUE THREAD

**Issue by HUMENTH** [fonoster/fonoster#638]
**Describe the bug**
unable to access console.fonoster.io

**To Reproduce**
1. Go to 'console.fonoster.io'
2. Then 'login with github account'
3. See error

**Expected behavior**
A Fonoster console page should be accessible.

**Screenshots**
![image](https://github.com/user-attachments/assets/fb835b4b-48f2-474e-96eb-f4c960b3cd09)

**Comment by psanders** [comment]
Thanks for reporting this. 
Solved.
