### ISSUE TITLE
[BUG]: Just installed with docker, "not found" on accessing web interface

### ISSUE THREAD

**Issue by orxaz** [fonoster/fonoster#647]
### What happened?

Just installed, when I access to APP_URL, got this:
*******************************
![imagen](https://github.com/user-attachments/assets/44f25f40-7d77-4f60-bdb6-ff6dd1dc40b0)
*******************************
![imagen](https://github.com/user-attachments/assets/d7e94918-1a55-4b39-9162-d8d6e65857c3)

### Steps to reproduce

1. Follow https://github.com/fonoster/fonoster/blob/main/docs/self-hosting/deploy-with-docker.md step by step
2. Access to http://localhost:8080 with Chrome or Firefox

### Expected behavior

The GUI being loaded

**Comment by psanders** [comment]
Sorry for the confusion. 

We don't yet have a WebUI (it is being rebuilt). 

I updated the self-hosting docs accordingly.

You can follow the progress around this topic [here](https://github.com/orgs/fonoster/discussions/646)
