### ISSUE TITLE
[FEATURE]: Create the Checkbox component for the Storybook

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#651]
### Is your feature request related to a problem?

This component is part of a reusable design system for Fonoster’s dashboard. It helps achieve consistency and reduces repetitive implementation work.

<img width="216" alt="Checkbox" src="https://github.com/user-attachments/assets/e8c31cc5-abbb-44f5-bbe0-fd0113aac6e9">

### Describe the solution you'd like

The Checkbox should follow the design in the Figma file and be implemented as a standalone React component with the following props: `onClick`

* It should use MUI styles for styling
* The component must have basic tests using

### Describe alternatives you've considered

NA

### Additional context

- Figma File: https://www.figma.com/design/OsZlne0RvIgoFlFKF7hnAU/Shared-Component-Library?node-id=276-26951&m=dev
- Acceptance Criteria: 
  - [x] Matches Figma design
  - [x] Storybook story with documentation
  - [ ] Works in light/dark themes
  - [ ] Includes basic unit tests
- Contributing Guidelines: https://github.com/fonoster/fonoster/blob/main/CONTRIBUTING.md

**Comment by CKanishka** [comment]
I can take this up

**Comment by psanders** [comment]
@CKanishka 

Deal! Assigned to you 🙌

**Comment by psanders** [comment]
@CKanishka merged 😊

You rock!
