### ISSUE TITLE
[FEATURE]: Create the Chip component for the Storybook

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#652]
### Is your feature request related to a problem?

This component is part of a reusable design system for Fonoster's dashboard. It helps achieve consistency and reduces repetitive implementation work.

<img width="161" alt="Chip" src="https://github.com/user-attachments/assets/02e614ad-1ca6-4a27-b623-856dbaf26521">

### Describe the solution you'd like

The Chip should follow the design in the Figma file and be implemented as a standalone React component with the following props: `onRemove`, `enabled`.

- It should use MUI styles for styling
- The component must have basic tests using

### Describe alternatives you've considered

NA

### Additional context

Before working on this item, please check the [CONTRIBUTING](https://github.com/fonoster/fonoster/blob/main/CONTRIBUTING.md) document. Details about the Chip component can be found [here.](https://www.figma.com/design/OsZlne0RvIgoFlFKF7hnAU/Shared-Component-Library?node-id=276-26951&m=dev)

Acceptance Criteria: 

  - [ ] Matches Figma design
  - [ ] Storybook story with documentation
  - [ ] Works in light/dark themes
  - [ ] Includes basic unit tests

**Comment by parz3val** [comment]
I will work on this.

**Comment by psanders** [comment]
@parz3val assigned to you 🙌

**Comment by parz3val** [comment]
@psanders I am guessing you missed the label string in the prop? I've added label as well in the props, and have opened a pr: #665

**Comment by psanders** [comment]
Good catch, @parz3val.

**Comment by psanders** [comment]
Close as completed by #665.
