### ISSUE TITLE
[FEATURE]: Create the GenericToggle component for the Storybook

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#653]
### Is your feature request related to a problem?

This component is part of a reusable design system for Fonoster's dashboard. It helps achieve consistency and reduces repetitive implementation work.

<img width="162" alt="GenericToggle" src="https://github.com/user-attachments/assets/c03eee95-d478-42aa-9292-f107173e6776">

### Describe the solution you'd like

The GenericToggle should follow the design in the Figma file and be implemented as a standalone React component with the following props: `defaultValue`, `value`, `onChange`, `disabled`.

* It should use MUI styles for styling
* The component must have basic tests using

### Describe alternatives you've considered

NA

### Additional context

Before working on this item, please check the [CONTRIBUTING](https://github.com/fonoster/fonoster/blob/main/CONTRIBUTING.md) document. Details about the GenericToggle component can be found [here.](https://www.figma.com/design/OsZlne0RvIgoFlFKF7hnAU/Shared-Component-Library?node-id=922-10843&m=dev)

Acceptance Criteria: 

  - [ ] Matches Figma design
  - [ ] Storybook story with documentation
  - [ ] Works in light/dark themes
  - [ ] Includes basic unit tests

**Comment by obrucheoghene** [comment]
Can I work on this

**Comment by psanders** [comment]
@obrucheoghene 

All your, friend 👊

**Comment by psanders** [comment]
Close as completed by https://github.com/fonoster/fonoster/pull/660
