### ISSUE TITLE
[FEATURE]: Create the LinkBackTo component for the Storybook

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#654]
### Is your feature request related to a problem?

This component is part of a reusable design system for Fonoster’s dashboard. It helps achieve consistency and reduces repetitive implementation work.

<img width="241" alt="LinkBackTo" src="https://github.com/user-attachments/assets/7968d2f6-8979-4ff4-a71c-53f27297e5c4">

### Describe the solution you'd like

The LinkBackTo should follow the design in the Figma file and be implemented as a standalone React component with the following props: `onClick`, `disabled`.

* It should use MUI styles for styling
* The component must have basic tests using

### Describe alternatives you've considered

NA

### Additional context

Before working on this item, please check the [CONTRIBUTING](https://github.com/fonoster/fonoster/blob/main/CONTRIBUTING.md) document. Details about the LinkBackTo component can be found [here.](https://www.figma.com/design/OsZlne0RvIgoFlFKF7hnAU/Shared-Component-Library?node-id=888-19698&m=dev)

Acceptance Criteria: 

  - [ ] Matches Figma design
  - [ ] Storybook story with documentation
  - [ ] Works in light/dark themes
  - [ ] Includes basic unit tests

**Comment by CKanishka** [comment]
I can work on this

**Comment by psanders** [comment]
@CKanishka Please do!
