### ISSUE TITLE
[FEATURE]: Create the LinkModalTrigger component for the Storybook

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#655]
### Is your feature request related to a problem?

This component is part of a reusable design system for Fonoster’s dashboard. It helps achieve consistency and reduces repetitive implementation work.

<img width="245" alt="LinkBackTrigger" src="https://github.com/user-attachments/assets/93d87a5d-bad4-4f07-a0d1-a651d9ff6f03">

### Describe the solution you'd like

The LinkBackTrigger should follow the design in the Figma file and be implemented as a standalone React component with the following props: `onClick`, `disabled`.

* It should use MUI styles for styling
* The component must have basic tests using

### Describe alternatives you've considered

NA

### Additional context

Before working on this item, please check the [CONTRIBUTING](https://github.com/fonoster/fonoster/blob/main/CONTRIBUTING.md) document. Details about the LinkBackTrigger component can be found [here.](https://www.figma.com/design/OsZlne0RvIgoFlFKF7hnAU/Shared-Component-Library?node-id=888-19702&m=dev)

Acceptance Criteria: 

  - [ ] Matches Figma design
  - [ ] Storybook story with documentation
  - [ ] Works in light/dark themes
  - [ ] Includes basic unit tests

**Comment by Nageswari-droid** [comment]
@psanders I can work on this issue

**Comment by psanders** [comment]
@Nageswari-droid, it is all yours 🙌

**Comment by psanders** [comment]
We are all set here. Thanks again @Nageswari-droid 🙏

(In relation to issue #679)
