### ISSUE TITLE
[FEATURE]: Create the OverviewCard component for the Storybook

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#657]
### Is your feature request related to a problem?

This component is part of a reusable design system for Fonoster's dashboard. It helps achieve consistency and reduces repetitive implementation work.

<img width="399" alt="OverviewCard" src="https://github.com/user-attachments/assets/7723253a-5df4-4782-ba06-947e0d56846a">

### Describe the solution you'd like

The OverviewCard should follow the design in the Figma file and be implemented as a standalone React component with the following props: `onClick`, `icon`, `label`.

* It should use MUI styles for styling
* The component must have basic tests using

### Describe alternatives you've considered

NA

### Additional context

Before working on this item, please check the [CONTRIBUTING](https://github.com/fonoster/fonoster/blob/main/CONTRIBUTING.md) document. Details about the OverviewCard component can be found [here.](https://www.figma.com/design/OsZlne0RvIgoFlFKF7hnAU/Shared-Component-Library?node-id=888-20517&m=dev)

Acceptance Criteria: 

  - [ ] Matches Figma design
  - [ ] Storybook story with documentation
  - [ ] Works in light/dark themes
  - [ ] Includes basic unit tests

**Comment by obrucheoghene** [comment]
I will like to work on this next

**Comment by psanders** [comment]
@obrucheoghene 

All your my friend!

**Comment by psanders** [comment]
Thanks again, @obrucheoghene.

You rock!

Closed as completed by #669
