### ISSUE TITLE
[BUG]: Paths Collision on a Case-insensitive filesystem

### ISSUE THREAD

**Issue by obrucheoghene** [fonoster/fonoster#659]
### What happened?

While cloning the repo on my mac, it logs this warning
```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'mods/identity/test/apikeys/listAPIKeys.test.ts'
  'mods/identity/test/apikeys/listApiKeys.test.ts'
  'mods/identity/test/apikeys/regenerateAPIKey.test.ts'
  'mods/identity/test/apikeys/regenerateApiKey.test.ts'
```
This is because, by default mac uses case-insensitive file system. 

<img width="563" alt="Screenshot 2024-12-06 at 7 06 38 PM" src="https://github.com/user-attachments/assets/3316ad94-93a3-4685-a62c-f8b08c04b877">

### Steps to reproduce

1. Clone the repo on mac

### Expected behavior

Clone in a case-insensitive filesystem without paths colliding

**Comment by obrucheoghene** [comment]
I have compared the colliding files and  they are exactly the same.

this
```
  'mods/identity/test/apikeys/listAPIKeys.test.ts'
  'mods/identity/test/apikeys/listApiKeys.test.ts'
 ```
and 
```
  'mods/identity/test/apikeys/regenerateAPIKey.test.ts'
  'mods/identity/test/apikeys/regenerateApiKey.test.ts'
```

Therefore deleting one of each will fix the issue
For consistency with naming convention of the other  test file, I recommend deleting 

```
  'mods/identity/test/apikeys/listAPIKeys.test.ts'
  'mods/identity/test/apikeys/regenerateAPIKey.test.ts'
 ```
  CC @psanders

**Comment by psanders** [comment]
@obrucheoghene 

How are you seeing these files? I looked for them with VS, directly in the command-line, and using GitHub to navigate the folders.

**Comment by obrucheoghene** [comment]
@psanders 
if you are on a mac, you will only see one of each most likely  ` 'mods/identity/test/apikeys/regenerateApiKey.test.ts'`  and ` 'mods/identity/test/apikeys/listApiKeys.test.ts'` because one overode the other.

But here they are on github file structure
<img width="329" alt="Screenshot 2024-12-09 at 11 19 08 AM" src="https://github.com/user-attachments/assets/44ca5790-777e-4505-88c0-70a4c5807526">

**Comment by psanders** [comment]
@obrucheoghene, I see it now! Thank you.

**Comment by parz3val** [comment]
@psanders I ran into the issue when I was trying to clone the repo on my mac to work on the dashboard components. I've removed the duplicate file with the same name and opened the pull request. Could you take a look at it? I won't be able to clone the repo without these changes.

**Comment by psanders** [comment]
Fantastic work, @parz3val. I still can't figure out how it doesn't show on my Mac.

I'm closing this as completed by #663.
