### ISSUE TITLE
[FEATURE]: Extend IconProps type with MUI SvgIconProps type

### ISSUE THREAD

**Issue by obrucheoghene** [fonoster/fonoster#668]
### Is your feature request related to a problem?

I encounter a blocker while building the OverviewCard component. 
I could not change the color of the icon to suit the design. This is because the Icon component do not accept color props.

Here is the Figma design with colored icon
![Screenshot 2024-12-14 at 10 53 05 PM](https://github.com/user-attachments/assets/622fc54a-784c-4618-8c93-672d2b7ed72a)

My design with default mui colored icon

![Screenshot 2024-12-14 at 10 54 19 PM](https://github.com/user-attachments/assets/f838bd15-396a-4a20-8b2d-2f2a1219685b)

### Describe the solution you'd like

Extending the IconProps type with MUI SvgIconProps type will make the Icon Component fully support all props available to Material-icon component. This will enable full customization of icons including changing of the colors

**Comment by obrucheoghene** [comment]
I will like to get this done

**Comment by psanders** [comment]
@obrucheoghene This makes sense to me. 

I merged the other PR.

As part of this feature, we should also update the OverviewCard.

**Comment by obrucheoghene** [comment]
Sure will as well

**Comment by psanders** [comment]
MVP!

Closed as completed by #670
