### ISSUE TITLE
[BUG]: Improve Error Message for Missing `.env` File

### ISSUE THREAD

**Issue by Nageswari-droid** [fonoster/fonoster#673]
### What happened?

When running the npm test command after npm run build, the process fails if the .env file is not created from .env.example.dev. Currently, the error message is vague, stating that the husky pre-commit hook fails, without explicitly mentioning the missing .env file. This can lead to confusion for developers.

### Steps to reproduce

1. Clone the project repository
2. Install all dependencies using `npm install`
3. Skip copying `.env.example.dev` to `.env`
4. Run `npm run build`
5. Run `npm test`

### Expected behavior

The error message should indicate that the `.env` file is missing and advise the developer to copy `.env.example.dev` to `.env`

**Comment by psanders** [comment]
@Nageswari-droid, 

Thank you for reporting. 

This is a very annoying issue. 

I can see two ways to solve this. We can either add a clear error that the file is missing or create the file automatically as a "prebuild" hook.

What do you think?

**Comment by Nageswari-droid** [comment]
@psanders I think automatically creating the file during the prebuild hook would be an efficient solution.

**Comment by justjordan15** [comment]
@Nageswari-droid Is this open to work on? I can take this if so!

**Comment by psanders** [comment]
@justjordan15 Assigned to you

As I agree with @Nageswari-droid. We should add a rebuild hook that checks if the `.env` files exist, and if it doesn't, it copies the `.env.example.dev` into it.

If the hook is too long, consider writing a script in the `.scripts` folder.

**Comment by justjordan15** [comment]
Ok, great I am starting on this.

**Comment by psanders** [comment]
@justjordan15 Does this help?

https://www.dropbox.com/s/wd6xaxx8uwy3wat/missing-env-details.mp4?st=rgdbd7mm&dl=0

**Comment by justjordan15** [comment]
@psanders Yes this helps a lot, I have been able to get an error message to display using the following in the package.json: 

"test": "node -e \"if (!require('fs').existsSync('.env')) { console.error('Error: .env file is missing from the root repository'); process.exit(1); }\" && cross-env LOGS_LEVEL=none NODE_ENV=dev mocha --timeout 30000 mods/**/*.test.ts


![Screenshot 2024-12-19 132713](https://github.com/user-attachments/assets/23fa4173-0936-4eeb-bc2f-0317bfda35f6)

Can I do the rebuild right in this test script?

**Comment by justjordan15** [comment]
@psanders Would someone be able to help me learn how to submit pull request or how I should go about getting my changes reviewed? I have looked at the documentation but am confused on how to do this in VS Code.

This is the updated error message if someone does not npm run build prior to npm test
![Screenshot 2024-12-19 143148](https://github.com/user-attachments/assets/bd178de3-3422-433b-83fc-cdfe9dae5548)

The build script checks to see if the .env file is there and if not it is added and copies the env.example.dev  to it. 
![Screenshot 2024-12-19 143631](https://github.com/user-attachments/assets/af48aa24-b7b8-4a2d-a068-7be991fbf91d)

finally, running npm test the tests are ran without an error.
![Screenshot 2024-12-19 143730](https://github.com/user-attachments/assets/e782af20-ddaf-4bab-9935-3ba297f2df80)

**Comment by psanders** [comment]
@justjordan15 This looks promising. Would you post this question on Discord? I want to get folks' input on this. 

However, generally speaking, you should:

- Create a fork of the project
- Commit your changes to it
- Then go to [PRs](https://github.com/fonoster/fonoster/pulls) and follow the form
- Interact with PR until it gets merged

I will make sure it gets reviewed quickly.

**Comment by justjordan15** [comment]
@psanders ok. Thank you!

**Comment by psanders** [comment]
All set here. Close by #680.
