### ISSUE TITLE
[FEATURE]: Create the ProgressIndicator component for the Storybook

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#676]
### Is your feature request related to a problem?

This component is part of a reusable design system for Fonoster’s dashboard. It helps achieve consistency and reduces repetitive implementation work.

<img width="785" alt="ProgressIndicator for onboarding" src="https://github.com/user-attachments/assets/6bb0a89b-1666-492e-8623-bd33e9fbb05c" />

### Describe the solution you'd like

The **ProgressIndicator** should follow the design in the Figma file and be implemented as a standalone React component with the following props: `step,` which is a numeric value of the current step (e.g., 1 == "verify email address.")

The closest component to this in MUI is the [Stepper](https://mui.com/material-ui/react-stepper/).

If appropriate, you might base this component on the Stepper or build the component from scratch.

### Describe alternatives you've considered

NA.

### Additional context

Before working on this item, please check the [CONTRIBUTING](https://github.com/fonoster/fonoster/blob/main/CONTRIBUTING.md) document. Details about the **ProgressIndicator** component can be found [here.](https://www.figma.com/design/OsZlne0RvIgoFlFKF7hnAU/Shared-Component-Library?node-id=16-11665&m=dev)

Acceptance Criteria: 

  - [ ] Matches Figma design
  - [ ] Storybook story with documentation
  - [ ] Includes basic unit tests (if applicable)

**Comment by obrucheoghene** [comment]
Hi @psanders 
I will take this.

**Comment by psanders** [comment]
@obrucheoghene all your, friend 🙏

**Comment by psanders** [comment]
All set here, my friend! 

Closed by #681.
