### ISSUE TITLE
[FEATURE]: Create the Snackbar component for the Storybook

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#678]
### Is your feature request related to a problem?

This component is part of a reusable design system for Fonoster’s dashboard. It helps achieve consistency and reduces repetitive implementation work.

<img width="357" alt="Snackbar Screenshot" src="https://github.com/user-attachments/assets/69b33b19-45f0-4504-948d-c6c75d283f5f" />

### Describe the solution you'd like

The **Snackbar** should follow the design in the Figma file and be implemented as a standalone React component with the following props: `message,` `open,` `onClose,` `position,` `autoHideDuration.`

The `position` prop will allow for the following values:

- top-left
- top-right
- top-center
- bottom-left
- bottom-right
- bottom-center

(Note1: Use the grow transition to bring in the component)
(Note2: At this point we only need a "close(x)" button and doesn't need to configurable)

### Describe alternatives you've considered

NA.

## Additional context

Before working on this item, please check the [CONTRIBUTING](https://github.com/fonoster/fonoster/blob/main/CONTRIBUTING.md) document. Details about the Snackbar component can be found [here.](https://www.figma.com/design/OsZlne0RvIgoFlFKF7hnAU/Shared-Component-Library?node-id=276-34326&m=dev)

Acceptance Criteria: 

  - [ ] Matches Figma design
  - [ ] Storybook story with documentation
  - [ ] Provide a story for every _position_ value
  - [ ] Includes basic unit tests (if applicable)

**Comment by Nageswari-droid** [comment]
@psanders Can I pick this card?

**Comment by psanders** [comment]
@Nageswari-droid, this one is fun. Ofc you can pick this card.

**Comment by Nageswari-droid** [comment]
@psanders Thanks!

**Comment by psanders** [comment]
All set here, @Nageswari-droid  🙌
