### ISSUE TITLE
[BUG]: Documentation and Getting Started guide doesn't open

### ISSUE THREAD

**Issue by arpanpreneur** [fonoster/fonoster#684]
### What happened?

The links https://fonoster.com/docs/overview are unavailable, because of which documentation is not browsable.

### Steps to reproduce

Click on https://fonoster.com/docs/overview are unavailable

### Expected behavior

To be able to view docs

**Comment by psanders** [comment]
@arpanpreneur Thanks for reporting this. 

I will look into this very soon.

**Comment by dipanshurdev** [comment]
Also "https://fonoster.com/docs/support" and "https://fonoster.com/docs/community" showing error "404 page not found"

**Comment by psanders** [comment]
@dipanshurdev @arpanpreneur 

Thanks for reporting the issue. The old docs are no longer helpful. I updated the website to point to a [GitHub Issue](https://github.com/fonoster/fonoster/issues/686) with useful information until the new docs go live.
