### ISSUE TITLE
Move token validation to Auth service

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#79]
**Description**

We need to move the token validation from the auth_middleware to the auth service. This is important to avoid having the authentication private key in too many places (since we presently separated the API into multiple services.)

I propose creating a new endpoint, under `/fonos.auth.v1alpha1.Auth/ValidateToken` and use this endpoint from the auth_middleware instead of directly accessing the private key.

@speedymonster, what are your thoughts?

**Comment by speedymonster** [comment]
I can make the change and as you mentioned, from the middleware make the request to the service to validate the token. I understand that it really is a better way to centralize the private key.

It is important to define the service and the protos.
